Globs:
  - src/**/*.cr
  - spec/**/*.cr
  - "!spec/unreachable.cr"

Documentation/DocumentationAdmonition:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false
